language: node_js

node_js:
  - 8

cache: npm

script:
  - npm run test

jobs:
  include:
    # Define the release stage that runs semantic-release
    - stage: release
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npm run build
          - npx semantic-release