language: node_js

node_js:
  - 8

cache: npm

jobs:
  include:
    - stage: test
      script:
        - npm run test
    # Define the release stage that runs semantic-release
    - stage: deploy
      node_js: lts/*
      # Advanced: optionally overwrite your default `script` step to skip the tests
      # script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release